# Site settings
title: Handbook

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-minifier
  - jekyll-github-metadata

permalink: pretty

jekyll-minifier:
  uglifier_args:
    harmony: true

search_enabled: true
aux_links:
  "Parallel Home": "https://about.parallelmarkets.com"

gtm_id: GTM-NLM5KSZ

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Makefile
  - README.md
